// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    login: "rahmancoder",
    id: 40750318,
    node_id: "MDQ6VXNlcjQwNzUwMzE4",
    avatar_url: "https://avatars.githubusercontent.com/u/40750318?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rahmancoder",
    html_url: "https://github.com/rahmancoder",
    followers_url: "https://api.github.com/users/rahmancoder/followers",
    following_url:
      "https://api.github.com/users/rahmancoder/following{/other_user}",
    gists_url: "https://api.github.com/users/rahmancoder/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/rahmancoder/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rahmancoder/subscriptions",
    organizations_url: "https://api.github.com/users/rahmancoder/orgs",
    repos_url: "https://api.github.com/users/rahmancoder/repos",
    events_url: "https://api.github.com/users/rahmancoder/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/rahmancoder/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "narangyawali",
    id: 58903698,
    node_id: "MDQ6VXNlcjU4OTAzNjk4",
    avatar_url: "https://avatars.githubusercontent.com/u/58903698?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/narangyawali",
    html_url: "https://github.com/narangyawali",
    followers_url: "https://api.github.com/users/narangyawali/followers",
    following_url:
      "https://api.github.com/users/narangyawali/following{/other_user}",
    gists_url: "https://api.github.com/users/narangyawali/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/narangyawali/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/narangyawali/subscriptions",
    organizations_url: "https://api.github.com/users/narangyawali/orgs",
    repos_url: "https://api.github.com/users/narangyawali/repos",
    events_url: "https://api.github.com/users/narangyawali/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/narangyawali/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Nicolae77",
    id: 67197181,
    node_id: "MDQ6VXNlcjY3MTk3MTgx",
    avatar_url: "https://avatars.githubusercontent.com/u/67197181?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Nicolae77",
    html_url: "https://github.com/Nicolae77",
    followers_url: "https://api.github.com/users/Nicolae77/followers",
    following_url:
      "https://api.github.com/users/Nicolae77/following{/other_user}",
    gists_url: "https://api.github.com/users/Nicolae77/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Nicolae77/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Nicolae77/subscriptions",
    organizations_url: "https://api.github.com/users/Nicolae77/orgs",
    repos_url: "https://api.github.com/users/Nicolae77/repos",
    events_url: "https://api.github.com/users/Nicolae77/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Nicolae77/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "aakash176",
    id: 76405780,
    node_id: "MDQ6VXNlcjc2NDA1Nzgw",
    avatar_url: "https://avatars.githubusercontent.com/u/76405780?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aakash176",
    html_url: "https://github.com/aakash176",
    followers_url: "https://api.github.com/users/aakash176/followers",
    following_url:
      "https://api.github.com/users/aakash176/following{/other_user}",
    gists_url: "https://api.github.com/users/aakash176/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/aakash176/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aakash176/subscriptions",
    organizations_url: "https://api.github.com/users/aakash176/orgs",
    repos_url: "https://api.github.com/users/aakash176/repos",
    events_url: "https://api.github.com/users/aakash176/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/aakash176/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Rajnish0202",
    id: 86077847,
    node_id: "MDQ6VXNlcjg2MDc3ODQ3",
    avatar_url: "https://avatars.githubusercontent.com/u/86077847?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Rajnish0202",
    html_url: "https://github.com/Rajnish0202",
    followers_url: "https://api.github.com/users/Rajnish0202/followers",
    following_url:
      "https://api.github.com/users/Rajnish0202/following{/other_user}",
    gists_url: "https://api.github.com/users/Rajnish0202/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Rajnish0202/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Rajnish0202/subscriptions",
    organizations_url: "https://api.github.com/users/Rajnish0202/orgs",
    repos_url: "https://api.github.com/users/Rajnish0202/repos",
    events_url: "https://api.github.com/users/Rajnish0202/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Rajnish0202/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dnipy",
    id: 86738036,
    node_id: "MDQ6VXNlcjg2NzM4MDM2",
    avatar_url: "https://avatars.githubusercontent.com/u/86738036?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dnipy",
    html_url: "https://github.com/dnipy",
    followers_url: "https://api.github.com/users/dnipy/followers",
    following_url: "https://api.github.com/users/dnipy/following{/other_user}",
    gists_url: "https://api.github.com/users/dnipy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dnipy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dnipy/subscriptions",
    organizations_url: "https://api.github.com/users/dnipy/orgs",
    repos_url: "https://api.github.com/users/dnipy/repos",
    events_url: "https://api.github.com/users/dnipy/events{/privacy}",
    received_events_url: "https://api.github.com/users/dnipy/received_events",
    type: "User",
    site_admin: false,
  },
];
