/* eslint-disable import/no-anonymous-default-export */
export default {
  "login": "sinaghaffarii",
  "id": 79760180,
  "node_id": "MDQ6VXNlcjc5NzYwMTgw",
  "avatar_url": "https://avatars.githubusercontent.com/u/79760180?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/sinaghaffarii",
  "html_url": "https://github.com/sinaghaffarii",
  "followers_url": "https://api.github.com/users/sinaghaffarii/followers",
  "following_url": "https://api.github.com/users/sinaghaffarii/following{/other_user}",
  "gists_url": "https://api.github.com/users/sinaghaffarii/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/sinaghaffarii/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/sinaghaffarii/subscriptions",
  "organizations_url": "https://api.github.com/users/sinaghaffarii/orgs",
  "repos_url": "https://api.github.com/users/sinaghaffarii/repos",
  "events_url": "https://api.github.com/users/sinaghaffarii/events{/privacy}",
  "received_events_url": "https://api.github.com/users/sinaghaffarii/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sina Ghaffari",
  "company": "Coding Addict",
  "blog": "www.linkedin.com/in/sina-ghaffariii",
  "location": "Tehran",
  "email": null,
  "hireable": null,
  "bio": "Love Conding",
  "twitter_username": "GhaffariMir",
  "public_repos": 29,
  "public_gists": 0,
  "followers": 6,
  "following": 7,
  "created_at": "2021-02-27T16:36:47Z",
  "updated_at": "2021-11-03T19:49:40Z"
};
